@startuml

skinparam {
          Shadowing false
          monochrome true
          StateBackgroundColor white
          StateBorderColor black
          ArrowColor black
          backgroundColor transparent
}

@enduml
